/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package view;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author Ould_Hamdi
 */
public class View extends javax.swing.JFrame {

    /** Creates new form View */
    public View() {
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupe = new javax.swing.ButtonGroup();
        fonctions = new javax.swing.ButtonGroup();
        uniteAngle = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        affichage = new javax.swing.JTextField();
        btnPlus = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnVirgule = new javax.swing.JButton();
        btnE = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btnFois = new javax.swing.JButton();
        btnMoins = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnAns = new javax.swing.JButton();
        btnEffacer = new javax.swing.JButton();
        btnEgale = new javax.swing.JButton();
        btnPuissance = new javax.swing.JButton();
        btnFact = new javax.swing.JButton();
        btnCarre = new javax.swing.JButton();
        btnPi = new javax.swing.JButton();
        btnRacCarre = new javax.swing.JButton();
        btnRacCube = new javax.swing.JButton();
        btnParenthese = new javax.swing.JButton();
        btnTan = new javax.swing.JButton();
        btnLog = new javax.swing.JButton();
        btnExp = new javax.swing.JButton();
        btnLn = new javax.swing.JButton();
        btnATan = new javax.swing.JButton();
        btnCos = new javax.swing.JButton();
        btnSin = new javax.swing.JButton();
        btnASin = new javax.swing.JButton();
        btnShift = new javax.swing.JButton();
        btnACos = new javax.swing.JButton();
        historique = new javax.swing.JComboBox<>();
        rad = new javax.swing.JRadioButton();
        deg = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ITEEM fx-2506");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        affichage.setFont(new java.awt.Font("3270 Nerd Font", 0, 48)); // NOI18N
        jPanel1.add(affichage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 270, 40));

        btnPlus.setBackground(new java.awt.Color(102, 102, 102));
        btnPlus.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnPlus.setText("+");
        groupe.add(btnPlus);
        jPanel1.add(btnPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 60, 40));

        btn1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn1.setText("1");
        groupe.add(btn1);
        jPanel1.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 60, 40));

        btn2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn2.setText("2");
        groupe.add(btn2);
        jPanel1.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 60, 40));

        btn3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn3.setText("3");
        groupe.add(btn3);
        jPanel1.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 60, 40));

        btn0.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn0.setText("0");
        groupe.add(btn0);
        jPanel1.add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 60, 40));

        btnVirgule.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnVirgule.setText(".");
        groupe.add(btnVirgule);
        jPanel1.add(btnVirgule, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 60, 40));

        btnE.setBackground(new java.awt.Color(0, 153, 153));
        btnE.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnE.setText("E");
        groupe.add(btnE);
        jPanel1.add(btnE, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 60, 40));

        btn6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn6.setText("6");
        groupe.add(btn6);
        jPanel1.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 60, 40));

        btn5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn5.setText("5");
        groupe.add(btn5);
        jPanel1.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 60, 40));

        btn4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn4.setText("4");
        groupe.add(btn4);
        jPanel1.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 60, 40));

        btn7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn7.setText("7");
        groupe.add(btn7);
        jPanel1.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 60, 40));

        btn8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn8.setText("8");
        groupe.add(btn8);
        jPanel1.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 60, 40));

        btn9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btn9.setText("9");
        groupe.add(btn9);
        jPanel1.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 60, 40));

        btnDiv.setBackground(new java.awt.Color(102, 102, 102));
        btnDiv.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnDiv.setText("/");
        groupe.add(btnDiv);
        jPanel1.add(btnDiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 60, 40));

        btnFois.setBackground(new java.awt.Color(102, 102, 102));
        btnFois.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnFois.setText("*");
        groupe.add(btnFois);
        jPanel1.add(btnFois, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 60, 40));

        btnMoins.setBackground(new java.awt.Color(102, 102, 102));
        btnMoins.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnMoins.setText("-");
        groupe.add(btnMoins);
        jPanel1.add(btnMoins, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 60, 40));

        btnClear.setBackground(new java.awt.Color(255, 0, 0));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnClear.setText("C");
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 60, 40));

        btnAns.setBackground(new java.awt.Color(0, 0, 204));
        btnAns.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAns.setText("Ans");
        btnAns.setMargin(new java.awt.Insets(2, 10, 3, 14));
        jPanel1.add(btnAns, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 60, 40));

        btnEffacer.setBackground(new java.awt.Color(255, 0, 0));
        btnEffacer.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnEffacer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/delete (2).png"))); // NOI18N
        jPanel1.add(btnEffacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 60, 40));

        btnEgale.setBackground(new java.awt.Color(51, 255, 0));
        btnEgale.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnEgale.setText("=");
        jPanel1.add(btnEgale, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 60, 40));

        btnPuissance.setBackground(new java.awt.Color(255, 102, 0));
        btnPuissance.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPuissance.setText("x^y");
        btnPuissance.setMargin(new java.awt.Insets(2, 10, 3, 14));
        jPanel1.add(btnPuissance, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 60, 40));

        btnFact.setBackground(new java.awt.Color(255, 102, 0));
        btnFact.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnFact.setText("x!");
        btnFact.setMargin(new java.awt.Insets(2, 10, 3, 14));
        jPanel1.add(btnFact, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 60, 40));

        btnCarre.setBackground(new java.awt.Color(255, 102, 0));
        btnCarre.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnCarre.setText("x²");
        jPanel1.add(btnCarre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 60, 40));

        btnPi.setBackground(new java.awt.Color(255, 153, 153));
        btnPi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnPi.setText("π");
        groupe.add(btnPi);
        jPanel1.add(btnPi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 60, 40));

        btnRacCarre.setBackground(new java.awt.Color(255, 102, 0));
        btnRacCarre.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRacCarre.setText("√");
        fonctions.add(btnRacCarre);
        jPanel1.add(btnRacCarre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 60, 40));

        btnRacCube.setBackground(new java.awt.Color(255, 102, 0));
        btnRacCube.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRacCube.setText("³√");
        fonctions.add(btnRacCube);
        jPanel1.add(btnRacCube, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 60, 40));

        btnParenthese.setBackground(new java.awt.Color(255, 102, 0));
        btnParenthese.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnParenthese.setText("( )");
        jPanel1.add(btnParenthese, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 60, 40));

        btnTan.setBackground(new java.awt.Color(153, 0, 255));
        btnTan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTan.setText("tan");
        fonctions.add(btnTan);
        btnTan.setMargin(new java.awt.Insets(2, 3, 3, 14));
        jPanel1.add(btnTan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 60, 40));

        btnLog.setBackground(new java.awt.Color(255, 204, 0));
        btnLog.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLog.setText("Log");
        fonctions.add(btnLog);
        btnLog.setMargin(new java.awt.Insets(2, 4, 3, 14));
        jPanel1.add(btnLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 60, 40));

        btnExp.setBackground(new java.awt.Color(255, 153, 153));
        btnExp.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        btnExp.setText("e");
        groupe.add(btnExp);
        jPanel1.add(btnExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 60, 40));

        btnLn.setBackground(new java.awt.Color(255, 204, 0));
        btnLn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnLn.setText("Ln");
        fonctions.add(btnLn);
        jPanel1.add(btnLn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 60, 40));

        btnATan.setBackground(new java.awt.Color(204, 153, 255));
        btnATan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnATan.setText("atan");
        fonctions.add(btnATan);
        btnATan.setMargin(new java.awt.Insets(2, 0, 3, 14));
        jPanel1.add(btnATan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 60, 40));

        btnCos.setBackground(new java.awt.Color(153, 0, 255));
        btnCos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCos.setText("cos");
        fonctions.add(btnCos);
        btnCos.setMargin(new java.awt.Insets(2, 3, 3, 14));
        jPanel1.add(btnCos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 60, 40));

        btnSin.setBackground(new java.awt.Color(153, 0, 255));
        btnSin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSin.setText("sin");
        fonctions.add(btnSin);
        btnSin.setMargin(new java.awt.Insets(2, 6, 3, 14));
        jPanel1.add(btnSin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 60, 40));

        btnASin.setBackground(new java.awt.Color(204, 153, 255));
        btnASin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnASin.setText("asin");
        fonctions.add(btnASin);
        btnASin.setMargin(new java.awt.Insets(2, 0, 3, 14));
        jPanel1.add(btnASin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 60, 40));

        btnShift.setBackground(new java.awt.Color(255, 255, 0));
        btnShift.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnShift.setText("Shift");
        btnShift.setMargin(new java.awt.Insets(2, 0, 3, 14));
        jPanel1.add(btnShift, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 20));

        btnACos.setBackground(new java.awt.Color(204, 153, 255));
        btnACos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnACos.setText("acos");
        fonctions.add(btnACos);
        btnACos.setMargin(new java.awt.Insets(2, 0, 3, 14));
        jPanel1.add(btnACos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 60, 40));

        historique.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "ViderHistorique" }));
        historique.setToolTipText("Historique de Calcule");
        jPanel1.add(historique, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 80, -1));

        uniteAngle.add(rad);
        rad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rad.setForeground(new java.awt.Color(255, 255, 255));
        rad.setText("Rad");
        rad.setActionCommand("rad");
        rad.setMargin(new java.awt.Insets(2, 0, 3, 2));
        jPanel1.add(rad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 50, -1));

        uniteAngle.add(deg);
        deg.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deg.setForeground(new java.awt.Color(255, 255, 255));
        deg.setSelected(true);
        deg.setText("Deg");
        deg.setActionCommand("deg");
        deg.setMargin(new java.awt.Insets(2, 0, 3, 2));
        jPanel1.add(deg, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 50, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField affichage;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnACos;
    private javax.swing.JButton btnASin;
    private javax.swing.JButton btnATan;
    private javax.swing.JButton btnAns;
    private javax.swing.JButton btnCarre;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCos;
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnEffacer;
    private javax.swing.JButton btnEgale;
    private javax.swing.JButton btnExp;
    private javax.swing.JButton btnFact;
    private javax.swing.JButton btnFois;
    private javax.swing.JButton btnLn;
    private javax.swing.JButton btnLog;
    private javax.swing.JButton btnMoins;
    private javax.swing.JButton btnParenthese;
    private javax.swing.JButton btnPi;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton btnPuissance;
    private javax.swing.JButton btnRacCarre;
    private javax.swing.JButton btnRacCube;
    private javax.swing.JButton btnShift;
    private javax.swing.JButton btnSin;
    private javax.swing.JButton btnTan;
    private javax.swing.JButton btnVirgule;
    private javax.swing.JRadioButton deg;
    private javax.swing.ButtonGroup fonctions;
    private javax.swing.ButtonGroup groupe;
    private javax.swing.JComboBox<String> historique;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rad;
    private javax.swing.ButtonGroup uniteAngle;
    // End of variables declaration//GEN-END:variables

    public JTextField getAffichage() {
        return affichage;
    }

    public JButton getBtnAns() {
        return btnAns;
    }

    public JButton getBtnCarre() {
        return btnCarre;
    }

    public JButton getBtnClear() {
        return btnClear;
    }

    public JButton getBtnEffacer() {
        return btnEffacer;
    }

    public JButton getBtnEgale() {
        return btnEgale;
    }

    public JButton getBtnFact() {
        return btnFact;
    }

    public JButton getBtnParenthese() {
        return btnParenthese;
    }

    public JButton getBtnPuissance() {
        return btnPuissance;
    }

    public JButton getBtnRacCarre() {
        return btnRacCarre;
    }

    public JButton getBtnRacCube() {
        return btnRacCube;
    }

    public JButton getBtnShift() {
        return btnShift;
    }

    public ButtonGroup getFonctions() {
        return fonctions;
    }

    public ButtonGroup getGroupe() {
        return groupe;
    }

    public JComboBox<String> getHistorique() {
        return historique;
    }

    public ButtonGroup getUniteAngle() {
        return uniteAngle;
    }

    public JButton getBtnACos() {
        return btnACos;
    }

    public JButton getBtnASin() {
        return btnASin;
    }

    public JButton getBtnATan() {
        return btnATan;
    }

    public JButton getBtnCos() {
        return btnCos;
    }

    public JButton getBtnSin() {
        return btnSin;
    }

    public JButton getBtnTan() {
        return btnTan;
    }
    
}
